version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auctify
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: auctify_be
    depends_on:
      - db
    environment:
      - PORT=7947
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=auctify
      - DB_PORT=3306
      - DB_URL=${DB_USER}:${DB_PASS}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}?charset=utf8mb4&parseTime=True&loc=Local
      - SECRET_KEY=1d0n7kn0wWh475h0uLd1Pu7H3r3
    ports:
      - "7947:7947"

volumes:
  db_data: {}